name: send telegram channel message
on:
  push:
    paths: '.github/workflows/telegram-channel.yml'
    branches: [tg-msg-action]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install got
      - uses: actions/github-script@v6
        with:
          script: |
            try {
              const { default: createTgChannelMsg } = await import('${{ github.workspace }}/scripts/tg-channel.js');
              await createTgChannelMsg(core)
              const got = await import('${{ github.workspace }}/node_modules/got')
              const text = process.env.tgMsg
              const response = await got.post('https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage', {
                "chat_id": "-1001522609970",
                text,
                "parse_mode": "HTML"
              }).text();
              core.info(stdout)
            }catch(error){
              core.setFailed(error.message);
            }
